//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_Tecnica_Bitsion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Persona
    {
        public int Id { get; set; }
        [Required]
        public string Nombres { get; set; }
        [Required]
        public string Apellidos { get; set; }
        public int Genero { get; set; }
        public int Estado { get; set; }
        public bool Manejar { get; set; }
        public bool Lentes { get; set; }
        public bool Diabetes { get; set; }
        public string Otras_Enfermedades { get; set; }
    
        public virtual EstadoPersona EstadoPersona { get; set; }
        public virtual Genero Genero1 { get; set; }
    }
}
